const CURRENCY_SYMBOLS: Record<string, string> = {
  USD: '$',
  EUR: '€',
  GBP: '£',
  CHF: 'Fr.',
  JPY: '¥',
  CNY: '¥',
  CAD: '$',
  AUD: '$',
  INR: '₹',
  HKD: 'HK$',
  KRW: '₩',
  SEK: 'kr',
  NOK: 'kr',
  DKK: 'kr',
  PLN: 'zł',
  BRL: 'R$',
  TWD: 'NT$',
  SGD: 'S$',
  NZD: 'NZ$',
  MXN: 'MX$',
  CZK: 'Kč',
  THB: '฿',
  ZAR: 'R',
  TRY: '₺',
  RUB: '₽',
};

export function getCurrencySymbol(currencyCode: string): string {
  return CURRENCY_SYMBOLS[currencyCode.toUpperCase()] || currencyCode;
}

export const SUPPORTED_CURRENCIES = [
  { code: 'USD', label: 'USD ($)' },
  { code: 'EUR', label: 'EUR (€)' },
  { code: 'GBP', label: 'GBP (£)' },
  { code: 'CHF', label: 'CHF (Fr.)' },
  { code: 'JPY', label: 'JPY (¥)' },
  { code: 'CNY', label: 'CNY (¥)' },
  { code: 'CAD', label: 'CAD ($)' },
  { code: 'AUD', label: 'AUD ($)' },
  { code: 'INR', label: 'INR (₹)' },
  { code: 'HKD', label: 'HKD (HK$)' },
  { code: 'KRW', label: 'KRW (₩)' },
  { code: 'SEK', label: 'SEK (kr)' },
  { code: 'NOK', label: 'NOK (kr)' },
  { code: 'DKK', label: 'DKK (kr)' },
  { code: 'PLN', label: 'PLN (zł)' },
  { code: 'BRL', label: 'BRL (R$)' },
  { code: 'TWD', label: 'TWD (NT$)' },
  { code: 'SGD', label: 'SGD (S$)' },
  { code: 'NZD', label: 'NZD (NZ$)' },
  { code: 'MXN', label: 'MXN (MX$)' },
  { code: 'CZK', label: 'CZK (Kč)' },
  { code: 'THB', label: 'THB (฿)' },
  { code: 'ZAR', label: 'ZAR (R)' },
  { code: 'TRY', label: 'TRY (₺)' },
  { code: 'RUB', label: 'RUB (₽)' },
] as const;
