"""Default spool and color catalog entries."""

# (name, weight_in_grams)
DEFAULT_SPOOL_CATALOG: list[tuple[str, int]] = [
    ("3D FilaPrint - Cardboard", 210),
    ("3D FilaPrint - Plastic", 238),
    ("3D Fuel - Plastic", 264),
    ("3D Power - Plastic", 220),
    ("3D Solutech - Plastic", 173),
    ("3DE - Cardboard", 136),
    ("3DE - Plastic", 181),
    ("3DHOJOR - Cardboard", 157),
    ("3DJake - Cardboard", 209),
    ("3DJake - Plastic", 232),
    ("3DJake 250g - Plastic", 91),
    ("3DJake ecoPLA - Plastic", 210),
    ("3DXTech - Plastic", 258),
    ("Acccreate - Plastic", 161),
    ("Amazon Basics - Plastic", 234),
    ("Amolen - Plastic", 150),
    ("AMZ3D - Plastic", 233),
    ("Anycubic - Cardboard", 125),
    ("Anycubic - Plastic", 127),
    ("Atomic Filament - Plastic", 272),
    ("Aurapol - Plastic", 220),
    ("Azure Film - Plastic", 163),
    ("Bambu Lab - Plastic High Temp", 216),
    ("Bambu Lab - Plastic Low Temp", 250),
    ("Bambu Lab - Plastic White", 253),
    ("BQ - Plastic", 218),
    ("Colorfabb - Plastic", 236),
    ("Colorfabb 750g - Cardboard", 152),
    ("Colorfabb 750g - Plastic", 254),
    ("Comgrow - Cardboard", 166),
    ("Creality - Cardboard", 180),
    ("Creality - Plastic", 135),
    ("Das Filament - Plastic", 211),
    ("Devil Design - Plastic", 256),
    ("Duramic 3D - Cardboard", 136),
    ("Elegoo - Cardboard", 153),
    ("Elegoo - Plastic", 111),
    ("Eryone - Cardboard", 156),
    ("Eryone - Plastic", 187),
    ("eSUN - Cardboard", 147),
    ("eSUN - Plastic", 240),
    ("eSUN 2.5kg - Plastic", 634),
    ("Extrudr - Plastic", 244),
    ("Fiberlogy - Plastic", 260),
    ("Filament PM - Plastic", 224),
    ("Fillamentum - Plastic", 230),
    ("Flashforge - Plastic", 167),
    ("FormFutura - Cardboard", 155),
    ("FormFutura 750g - Plastic", 212),
    ("Geeetech - Plastic", 178),
    ("Gembird - Cardboard", 143),
    ("Hatchbox - Plastic", 225),
    ("Inland - Cardboard", 142),
    ("Inland - Plastic", 210),
    ("Jayo - Cardboard", 120),
    ("Jayo - Plastic", 126),
    ("Jayo 250g - Plastic", 58),
    ("Kingroon - Cardboard", 155),
    ("Kingroon - Plastic", 156),
    ("KVP - Plastic", 263),
    ("Matter Hackers - Plastic", 215),
    ("MG Chemicals - Cardboard", 150),
    ("MG Chemicals - Plastic", 239),
    ("Mika3D - Plastic", 175),
    ("MonoPrice - Plastic", 221),
    ("Overture - Cardboard", 150),
    ("Overture - Plastic", 237),
    ("PolyMaker - Cardboard", 137),
    ("PolyMaker - Plastic", 220),
    ("PolyMaker 3kg - Cardboard", 418),
    ("PolyTerra PLA - Cardboard", 147),
    ("PrimaSelect - Plastic", 222),
    ("ProtoPasta - Cardboard", 80),
    ("Prusament - Plastic", 201),
    ("Prusament - Plastic w/ Cardboard Core", 196),
    ("Rosa3D - Plastic", 245),
    ("Sakata3D - Plastic", 205),
    ("Snapmaker - Cardboard", 148),
    ("Sovol - Cardboard", 145),
    ("Spectrum - Cardboard", 180),
    ("Spectrum - Plastic", 257),
    ("Sunlu - Plastic", 117),
    ("Sunlu - Plastic V2", 165),
    ("Sunlu - Plastic V3", 179),
    ("Sunlu 250g - Plastic", 55),
    ("UltiMaker - Plastic", 235),
    ("Voolt3D - Plastic", 190),
    ("Voxelab - Plastic", 171),
    ("Wanhao - Plastic", 267),
    ("Ziro - Plastic", 166),
    ("ZYLtech - Plastic", 179),
]

# (manufacturer, color_name, hex_color, material)
DEFAULT_COLOR_CATALOG: list[tuple[str, str, str, str]] = [
    # Bambu Lab PLA Basic (from official hex code PDF)
    ("Bambu Lab", "Jade White", "#FFFFFF", "PLA Basic"),
    ("Bambu Lab", "Black", "#000000", "PLA Basic"),
    ("Bambu Lab", "Silver", "#A6A9AA", "PLA Basic"),
    ("Bambu Lab", "Light Gray", "#D1D3D5", "PLA Basic"),
    ("Bambu Lab", "Gray", "#8E9089", "PLA Basic"),
    ("Bambu Lab", "Dark Gray", "#545454", "PLA Basic"),
    ("Bambu Lab", "Red", "#C12E1F", "PLA Basic"),
    ("Bambu Lab", "Maroon Red", "#9D2235", "PLA Basic"),
    ("Bambu Lab", "Magenta", "#EC008C", "PLA Basic"),
    ("Bambu Lab", "Hot Pink", "#F5547C", "PLA Basic"),
    ("Bambu Lab", "Pink", "#F55A74", "PLA Basic"),
    ("Bambu Lab", "Beige", "#F7E6DE", "PLA Basic"),
    ("Bambu Lab", "Yellow", "#F4EE2A", "PLA Basic"),
    ("Bambu Lab", "Sunflower Yellow", "#FEC600", "PLA Basic"),
    ("Bambu Lab", "Gold", "#E4BD68", "PLA Basic"),
    ("Bambu Lab", "Orange", "#FF6A13", "PLA Basic"),
    ("Bambu Lab", "Pumpkin Orange", "#FF9016", "PLA Basic"),
    ("Bambu Lab", "Bright Green", "#BECF00", "PLA Basic"),
    ("Bambu Lab", "Bambu Green", "#00AE42", "PLA Basic"),
    ("Bambu Lab", "Mistletoe Green", "#3F8E43", "PLA Basic"),
    ("Bambu Lab", "Turquoise", "#00B1B7", "PLA Basic"),
    ("Bambu Lab", "Cyan", "#0086D6", "PLA Basic"),
    ("Bambu Lab", "Blue", "#0A2989", "PLA Basic"),
    ("Bambu Lab", "Blue Grey", "#5B6579", "PLA Basic"),
    ("Bambu Lab", "Cobalt Blue", "#0056B8", "PLA Basic"),
    ("Bambu Lab", "Purple", "#5E43B7", "PLA Basic"),
    ("Bambu Lab", "Indigo Purple", "#482960", "PLA Basic"),
    ("Bambu Lab", "Brown", "#9D432C", "PLA Basic"),
    ("Bambu Lab", "Cocoa Brown", "#6F5034", "PLA Basic"),
    ("Bambu Lab", "Bronze", "#847D48", "PLA Basic"),
    # Bambu Lab PLA Matte (from official hex code PDF)
    ("Bambu Lab", "Ivory White", "#FFFFFF", "PLA Matte"),
    ("Bambu Lab", "Bone White", "#CBC6B8", "PLA Matte"),
    ("Bambu Lab", "Desert Tan", "#E8DBB7", "PLA Matte"),
    ("Bambu Lab", "Latte Brown", "#D3B7A7", "PLA Matte"),
    ("Bambu Lab", "Caramel", "#AE835B", "PLA Matte"),
    ("Bambu Lab", "Terracotta", "#B15533", "PLA Matte"),
    ("Bambu Lab", "Dark Brown", "#7D6556", "PLA Matte"),
    ("Bambu Lab", "Dark Chocolate", "#4D3324", "PLA Matte"),
    ("Bambu Lab", "Lilac Purple", "#AE96D4", "PLA Matte"),
    ("Bambu Lab", "Sakura Pink", "#E8AFCF", "PLA Matte"),
    ("Bambu Lab", "Mandarin Orange", "#F99963", "PLA Matte"),
    ("Bambu Lab", "Lemon Yellow", "#F7D959", "PLA Matte"),
    ("Bambu Lab", "Plum", "#950051", "PLA Matte"),
    ("Bambu Lab", "Scarlet Red", "#DE4343", "PLA Matte"),
    ("Bambu Lab", "Dark Red", "#BB3D43", "PLA Matte"),
    ("Bambu Lab", "Dark Green", "#68724D", "PLA Matte"),
    ("Bambu Lab", "Grass Green", "#61C680", "PLA Matte"),
    ("Bambu Lab", "Apple Green", "#C2E189", "PLA Matte"),
    ("Bambu Lab", "Ice Blue", "#A3D8E1", "PLA Matte"),
    ("Bambu Lab", "Sky Blue", "#56B7E6", "PLA Matte"),
    ("Bambu Lab", "Marine Blue", "#0078BF", "PLA Matte"),
    ("Bambu Lab", "Dark Blue", "#042F56", "PLA Matte"),
    ("Bambu Lab", "Ash Gray", "#9B9EA0", "PLA Matte"),
    ("Bambu Lab", "Nardo Gray", "#757575", "PLA Matte"),
    ("Bambu Lab", "Charcoal", "#000000", "PLA Matte"),
    # Bambu Lab PLA Silk+ (from store page)
    ("Bambu Lab", "Gold", "#F4A925", "PLA Silk"),
    ("Bambu Lab", "Silver", "#C8C8C8", "PLA Silk"),
    ("Bambu Lab", "Titan Gray", "#5F6367", "PLA Silk"),
    ("Bambu Lab", "Blue", "#008BDA", "PLA Silk"),
    ("Bambu Lab", "Purple", "#8671CB", "PLA Silk"),
    ("Bambu Lab", "Candy Red", "#D02727", "PLA Silk"),
    ("Bambu Lab", "Candy Green", "#018814", "PLA Silk"),
    ("Bambu Lab", "Rose Gold", "#BA9594", "PLA Silk"),
    ("Bambu Lab", "Baby Blue", "#A8C6EE", "PLA Silk"),
    ("Bambu Lab", "Pink", "#F7ADA6", "PLA Silk"),
    ("Bambu Lab", "Mint", "#96DCB9", "PLA Silk"),
    ("Bambu Lab", "Champagne", "#F3CFB2", "PLA Silk"),
    ("Bambu Lab", "White", "#FFFFFF", "PLA Silk"),
    # Bambu Lab PLA Sparkle (from store page)
    ("Bambu Lab", "Classic Gold Sparkle", "#CEA629", "PLA Sparkle"),
    ("Bambu Lab", "Slate Gray Sparkle", "#8E9089", "PLA Sparkle"),
    ("Bambu Lab", "Crimson Red Sparkle", "#792B36", "PLA Sparkle"),
    ("Bambu Lab", "Royal Purple Sparkle", "#483D8B", "PLA Sparkle"),
    ("Bambu Lab", "Alpine Green Sparkle", "#3F5443", "PLA Sparkle"),
    ("Bambu Lab", "Onyx Black Sparkle", "#2D2B28", "PLA Sparkle"),
    # Bambu Lab PLA Translucent (from official hex code PDF)
    ("Bambu Lab", "Teal", "#009FA1", "PLA Translucent"),
    ("Bambu Lab", "Light Jade", "#96D8AF", "PLA Translucent"),
    ("Bambu Lab", "Blue", "#0047BB", "PLA Translucent"),
    ("Bambu Lab", "Mellow Yellow", "#F5DBAB", "PLA Translucent"),
    ("Bambu Lab", "Purple", "#8344B0", "PLA Translucent"),
    ("Bambu Lab", "Cherry Pink", "#F5B6CD", "PLA Translucent"),
    ("Bambu Lab", "Orange", "#F74E02", "PLA Translucent"),
    ("Bambu Lab", "Ice Blue", "#B8CDE9", "PLA Translucent"),
    ("Bambu Lab", "Red", "#B50011", "PLA Translucent"),
    ("Bambu Lab", "Lavender", "#B8ACD6", "PLA Translucent"),
    # Bambu Lab PLA Glow (from store page)
    ("Bambu Lab", "Glow Green", "#A1FFAC", "PLA Glow"),
    ("Bambu Lab", "Glow Yellow", "#F8FF80", "PLA Glow"),
    ("Bambu Lab", "Glow Pink", "#F17B8F", "PLA Glow"),
    ("Bambu Lab", "Glow Blue", "#7AC0E9", "PLA Glow"),
    ("Bambu Lab", "Glow Orange", "#FF9D5B", "PLA Glow"),
    # Bambu Lab PLA Galaxy (from store page)
    ("Bambu Lab", "Brown", "#684A43", "PLA Galaxy"),
    ("Bambu Lab", "Green", "#3B665E", "PLA Galaxy"),
    ("Bambu Lab", "Nebulae", "#424379", "PLA Galaxy"),
    ("Bambu Lab", "Purple", "#594177", "PLA Galaxy"),
    # Bambu Lab PLA Metal (from store page)
    ("Bambu Lab", "Iridium Gold Metallic", "#B39B84", "PLA Metal"),
    ("Bambu Lab", "Copper Brown Metallic", "#AA6443", "PLA Metal"),
    ("Bambu Lab", "Oxide Green Metallic", "#1D7C6A", "PLA Metal"),
    ("Bambu Lab", "Cobalt Blue Metallic", "#39699E", "PLA Metal"),
    ("Bambu Lab", "Iron Gray Metallic", "#43403D", "PLA Metal"),
    # Bambu Lab PLA Marble (from store page)
    ("Bambu Lab", "White Marble", "#F7F3F0", "PLA Marble"),
    ("Bambu Lab", "Red Granite", "#AD4E38", "PLA Marble"),
    # Bambu Lab PLA Wood (from store page)
    ("Bambu Lab", "Black Walnut", "#4F3F24", "PLA Wood"),
    ("Bambu Lab", "Rosewood", "#4C241C", "PLA Wood"),
    ("Bambu Lab", "Clay Brown", "#995F11", "PLA Wood"),
    ("Bambu Lab", "Classic Birch", "#918669", "PLA Wood"),
    ("Bambu Lab", "White Oak", "#D6CCA3", "PLA Wood"),
    ("Bambu Lab", "Ochre Yellow", "#C98935", "PLA Wood"),
    # Bambu Lab PLA Tough+ (from official hex code PDF)
    ("Bambu Lab", "White", "#FFFFFF", "PLA Tough"),
    ("Bambu Lab", "Gray", "#AFB1AE", "PLA Tough"),
    ("Bambu Lab", "Black", "#000000", "PLA Tough"),
    ("Bambu Lab", "Silver", "#959698", "PLA Tough"),
    ("Bambu Lab", "Yellow", "#F4D53F", "PLA Tough"),
    ("Bambu Lab", "Cyan", "#009BD8", "PLA Tough"),
    ("Bambu Lab", "Orange", "#DC3A27", "PLA Tough"),
    # Bambu Lab PLA-CF (from official hex code PDF)
    ("Bambu Lab", "Burgundy Red", "#951E23", "PLA-CF"),
    ("Bambu Lab", "Iris Purple", "#69398E", "PLA-CF"),
    ("Bambu Lab", "Matcha Green", "#5C9748", "PLA-CF"),
    ("Bambu Lab", "Jeans Blue", "#6E88BC", "PLA-CF"),
    ("Bambu Lab", "Royal Blue", "#2842AD", "PLA-CF"),
    ("Bambu Lab", "Lava Gray", "#4D5054", "PLA-CF"),
    ("Bambu Lab", "Black", "#000000", "PLA-CF"),
    # Bambu Lab ABS (from official hex code PDF)
    ("Bambu Lab", "White", "#FFFFFF", "ABS"),
    ("Bambu Lab", "Desert Tan", "#E8DBB7", "ABS"),
    ("Bambu Lab", "Olive", "#789D4A", "ABS"),
    ("Bambu Lab", "Azure", "#489FDF", "ABS"),
    ("Bambu Lab", "Navy Blue", "#0C2340", "ABS"),
    ("Bambu Lab", "Blue", "#0A2CA5", "ABS"),
    ("Bambu Lab", "Tangerine Yellow", "#FFC72C", "ABS"),
    ("Bambu Lab", "Orange", "#FF6A13", "ABS"),
    ("Bambu Lab", "Red", "#D32941", "ABS"),
    ("Bambu Lab", "Purple", "#AF1685", "ABS"),
    ("Bambu Lab", "Silver", "#87909A", "ABS"),
    ("Bambu Lab", "Black", "#000000", "ABS"),
    # Bambu Lab ASA (from store page)
    ("Bambu Lab", "White", "#FFFAF2", "ASA"),
    ("Bambu Lab", "Gray", "#8A949E", "ASA"),
    ("Bambu Lab", "Red", "#E02928", "ASA"),
    ("Bambu Lab", "Green", "#00A6A0", "ASA"),
    ("Bambu Lab", "Blue", "#2140B4", "ASA"),
    ("Bambu Lab", "Black", "#000000", "ASA"),
    # Bambu Lab PETG HF (from store page)
    ("Bambu Lab", "Yellow", "#FFD00B", "PETG HF"),
    ("Bambu Lab", "Orange", "#F75403", "PETG HF"),
    ("Bambu Lab", "Green", "#00AE42", "PETG HF"),
    ("Bambu Lab", "Red", "#EB3A3A", "PETG HF"),
    ("Bambu Lab", "Blue", "#002E96", "PETG HF"),
    ("Bambu Lab", "Black", "#000000", "PETG HF"),
    ("Bambu Lab", "White", "#FFFFFF", "PETG HF"),
    ("Bambu Lab", "Cream", "#F9DFB9", "PETG HF"),
    ("Bambu Lab", "Lime Green", "#6EE53C", "PETG HF"),
    ("Bambu Lab", "Forest Green", "#39541A", "PETG HF"),
    ("Bambu Lab", "Lake Blue", "#1F79E5", "PETG HF"),
    ("Bambu Lab", "Peanut Brown", "#875718", "PETG HF"),
    ("Bambu Lab", "Gray", "#ADB1B2", "PETG HF"),
    ("Bambu Lab", "Dark Gray", "#515151", "PETG HF"),
    # Bambu Lab PETG Translucent (from store page)
    ("Bambu Lab", "Translucent Gray", "#8E8E8E", "PETG Translucent"),
    ("Bambu Lab", "Translucent Light Blue", "#61B0FF", "PETG Translucent"),
    ("Bambu Lab", "Translucent Olive", "#748C45", "PETG Translucent"),
    ("Bambu Lab", "Translucent Brown", "#C9A381", "PETG Translucent"),
    ("Bambu Lab", "Translucent Teal", "#77EDD7", "PETG Translucent"),
    ("Bambu Lab", "Translucent Orange", "#FF911A", "PETG Translucent"),
    ("Bambu Lab", "Translucent Purple", "#D6ABFF", "PETG Translucent"),
    ("Bambu Lab", "Translucent Pink", "#F9C1BD", "PETG Translucent"),
    # Bambu Lab PETG-CF (from official hex code PDF)
    ("Bambu Lab", "Brick Red", "#9F332A", "PETG-CF"),
    ("Bambu Lab", "Violet Purple", "#583061", "PETG-CF"),
    ("Bambu Lab", "Indigo Blue", "#324585", "PETG-CF"),
    ("Bambu Lab", "Malachite Green", "#16B08E", "PETG-CF"),
    ("Bambu Lab", "Black", "#000000", "PETG-CF"),
    ("Bambu Lab", "Titan Gray", "#565656", "PETG-CF"),
    # Bambu Lab TPU 95A HF (from store page)
    ("Bambu Lab", "White", "#FFFFFF", "TPU 95A"),
    ("Bambu Lab", "Yellow", "#F3E600", "TPU 95A"),
    ("Bambu Lab", "Blue", "#0072CE", "TPU 95A"),
    ("Bambu Lab", "Red", "#C8102E", "TPU 95A"),
    ("Bambu Lab", "Gray", "#898D8D", "TPU 95A"),
    ("Bambu Lab", "Black", "#101820", "TPU 95A"),
    # Bambu Lab TPU 90A (from official hex code PDF)
    ("Bambu Lab", "Black", "#000000", "TPU 90A"),
    ("Bambu Lab", "White", "#FFFFFF", "TPU 90A"),
    ("Bambu Lab", "Grape Jelly", "#D6ABFF", "TPU 90A"),
    ("Bambu Lab", "Crystal Blue", "#7EB4E1", "TPU 90A"),
    ("Bambu Lab", "Cocoa Brown", "#5C4738", "TPU 90A"),
    # Bambu Lab PAHT-CF
    ("Bambu Lab", "Black", "#1A1A1A", "PAHT-CF"),
    # Bambu Lab Support Materials
    ("Bambu Lab", "Natural", "#F5F5DC", "PLA Support"),
    ("Bambu Lab", "Natural", "#F5F5DC", "PVA Support"),
    # Polymaker PolyTerra PLA
    ("Polymaker", "Cotton White", "#F5F5F5", "PolyTerra PLA"),
    ("Polymaker", "Charcoal Black", "#2B2B2B", "PolyTerra PLA"),
    ("Polymaker", "Marble White", "#E8E8E8", "PolyTerra PLA"),
    ("Polymaker", "Fossil Grey", "#6B6B6B", "PolyTerra PLA"),
    ("Polymaker", "Shadow Black", "#1A1A1A", "PolyTerra PLA"),
    ("Polymaker", "Army Red", "#8B0000", "PolyTerra PLA"),
    ("Polymaker", "Lava Red", "#CF1020", "PolyTerra PLA"),
    ("Polymaker", "Sakura Pink", "#FFB7C5", "PolyTerra PLA"),
    ("Polymaker", "Rose", "#FF007F", "PolyTerra PLA"),
    ("Polymaker", "Peach", "#FFCBA4", "PolyTerra PLA"),
    ("Polymaker", "Banana", "#FFE135", "PolyTerra PLA"),
    ("Polymaker", "Savannah Yellow", "#F4C430", "PolyTerra PLA"),
    ("Polymaker", "Sunrise Orange", "#FF6600", "PolyTerra PLA"),
    ("Polymaker", "Muted Green", "#4F7942", "PolyTerra PLA"),
    ("Polymaker", "Forest Green", "#228B22", "PolyTerra PLA"),
    ("Polymaker", "Mint", "#98FF98", "PolyTerra PLA"),
    ("Polymaker", "Lavender Purple", "#B57EDC", "PolyTerra PLA"),
    ("Polymaker", "Sapphire Blue", "#0F52BA", "PolyTerra PLA"),
    ("Polymaker", "Ice", "#D6ECEF", "PolyTerra PLA"),
    # Prusament PLA
    ("Prusament", "Jet Black", "#1A1A1A", "PLA"),
    ("Prusament", "Galaxy Black", "#1F1F1F", "PLA"),
    ("Prusament", "Pristine White", "#FFFFFF", "PLA"),
    ("Prusament", "Gentleman's Grey", "#5A5A5A", "PLA"),
    ("Prusament", "Lipstick Red", "#C21E1E", "PLA"),
    ("Prusament", "Orange", "#FF6600", "PLA"),
    ("Prusament", "Pineapple Yellow", "#FFD700", "PLA"),
    ("Prusament", "Jungle Green", "#29AB87", "PLA"),
    ("Prusament", "Azure Blue", "#007FFF", "PLA"),
    ("Prusament", "Royal Blue", "#4169E1", "PLA"),
    ("Prusament", "Mystic Purple", "#7B68EE", "PLA"),
    # eSUN PLA+
    ("eSUN", "White", "#FFFFFF", "PLA+"),
    ("eSUN", "Black", "#000000", "PLA+"),
    ("eSUN", "Grey", "#808080", "PLA+"),
    ("eSUN", "Red", "#FF0000", "PLA+"),
    ("eSUN", "Blue", "#0000FF", "PLA+"),
    ("eSUN", "Green", "#00FF00", "PLA+"),
    ("eSUN", "Yellow", "#FFFF00", "PLA+"),
    ("eSUN", "Orange", "#FFA500", "PLA+"),
    ("eSUN", "Purple", "#800080", "PLA+"),
    ("eSUN", "Pink", "#FFC0CB", "PLA+"),
    # Hatchbox PLA
    ("Hatchbox", "White", "#FFFFFF", "PLA"),
    ("Hatchbox", "Black", "#000000", "PLA"),
    ("Hatchbox", "Gray", "#808080", "PLA"),
    ("Hatchbox", "Red", "#FF0000", "PLA"),
    ("Hatchbox", "Blue", "#0000FF", "PLA"),
    ("Hatchbox", "Green", "#00FF00", "PLA"),
    ("Hatchbox", "Yellow", "#FFFF00", "PLA"),
    ("Hatchbox", "Orange", "#FFA500", "PLA"),
    ("Hatchbox", "Purple", "#800080", "PLA"),
    ("Hatchbox", "Pink", "#FFC0CB", "PLA"),
    ("Hatchbox", "True Blue", "#0073CF", "PLA"),
    ("Hatchbox", "True Green", "#008000", "PLA"),
]
