"""Default spool and color catalog entries."""

# (name, weight_in_grams)
DEFAULT_SPOOL_CATALOG: list[tuple[str, int]] = [
    ("3D FilaPrint - Cardboard", 210),
    ("3D FilaPrint - Plastic", 238),
    ("3D Fuel - Plastic", 264),
    ("3D Power - Plastic", 220),
    ("3D Solutech - Plastic", 173),
    ("3DE - Cardboard", 136),
    ("3DE - Plastic", 181),
    ("3DHOJOR - Cardboard", 157),
    ("3DJake - Cardboard", 209),
    ("3DJake - Plastic", 232),
    ("3DJake 250g - Plastic", 91),
    ("3DJake ecoPLA - Plastic", 210),
    ("3DXTech - Plastic", 258),
    ("Acccreate - Plastic", 161),
    ("Amazon Basics - Plastic", 234),
    ("Amolen - Plastic", 150),
    ("AMZ3D - Plastic", 233),
    ("Anycubic - Cardboard", 125),
    ("Anycubic - Plastic", 127),
    ("Atomic Filament - Plastic", 272),
    ("Aurapol - Plastic", 220),
    ("Azure Film - Plastic", 163),
    ("Bambu Lab - Plastic High Temp", 216),
    ("Bambu Lab - Plastic Low Temp", 250),
    ("Bambu Lab - Plastic White", 253),
    ("BQ - Plastic", 218),
    ("Colorfabb - Plastic", 236),
    ("Colorfabb 750g - Cardboard", 152),
    ("Colorfabb 750g - Plastic", 254),
    ("Comgrow - Cardboard", 166),
    ("Creality - Cardboard", 180),
    ("Creality - Plastic", 135),
    ("Das Filament - Plastic", 211),
    ("Devil Design - Plastic", 256),
    ("Duramic 3D - Cardboard", 136),
    ("Elegoo - Cardboard", 153),
    ("Elegoo - Plastic", 111),
    ("Eryone - Cardboard", 156),
    ("Eryone - Plastic", 187),
    ("eSUN - Cardboard", 147),
    ("eSUN - Plastic", 240),
    ("eSUN 2.5kg - Plastic", 634),
    ("Extrudr - Plastic", 244),
    ("Fiberlogy - Plastic", 260),
    ("Filament PM - Plastic", 224),
    ("Fillamentum - Plastic", 230),
    ("Flashforge - Plastic", 167),
    ("FormFutura - Cardboard", 155),
    ("FormFutura 750g - Plastic", 212),
    ("Geeetech - Plastic", 178),
    ("Gembird - Cardboard", 143),
    ("Hatchbox - Plastic", 225),
    ("Inland - Cardboard", 142),
    ("Inland - Plastic", 210),
    ("Jayo - Cardboard", 120),
    ("Jayo - Plastic", 126),
    ("Jayo 250g - Plastic", 58),
    ("Kingroon - Cardboard", 155),
    ("Kingroon - Plastic", 156),
    ("KVP - Plastic", 263),
    ("Matter Hackers - Plastic", 215),
    ("MG Chemicals - Cardboard", 150),
    ("MG Chemicals - Plastic", 239),
    ("Mika3D - Plastic", 175),
    ("MonoPrice - Plastic", 221),
    ("Overture - Cardboard", 150),
    ("Overture - Plastic", 237),
    ("PolyMaker - Cardboard", 137),
    ("PolyMaker - Plastic", 220),
    ("PolyMaker 3kg - Cardboard", 418),
    ("PolyTerra PLA - Cardboard", 147),
    ("PrimaSelect - Plastic", 222),
    ("ProtoPasta - Cardboard", 80),
    ("Prusament - Plastic", 201),
    ("Prusament - Plastic w/ Cardboard Core", 196),
    ("Rosa3D - Plastic", 245),
    ("Sakata3D - Plastic", 205),
    ("Snapmaker - Cardboard", 148),
    ("Sovol - Cardboard", 145),
    ("Spectrum - Cardboard", 180),
    ("Spectrum - Plastic", 257),
    ("Sunlu - Plastic", 117),
    ("Sunlu - Plastic V2", 165),
    ("Sunlu - Plastic V3", 179),
    ("Sunlu 250g - Plastic", 55),
    ("UltiMaker - Plastic", 235),
    ("Voolt3D - Plastic", 190),
    ("Voxelab - Plastic", 171),
    ("Wanhao - Plastic", 267),
    ("Ziro - Plastic", 166),
    ("ZYLtech - Plastic", 179),
]

# (manufacturer, color_name, hex_color, material)
DEFAULT_COLOR_CATALOG: list[tuple[str, str, str, str]] = [
    # Bambu Lab PLA Basic (from official hex code PDF)
    ("Bambu Lab", "Jade White", "#FFFFFF", "PLA Basic"),
    ("Bambu Lab", "Black", "#000000", "PLA Basic"),
    ("Bambu Lab", "Silver", "#A6A9AA", "PLA Basic"),
    ("Bambu Lab", "Light Gray", "#D1D3D5", "PLA Basic"),
    ("Bambu Lab", "Gray", "#8E9089", "PLA Basic"),
    ("Bambu Lab", "Dark Gray", "#545454", "PLA Basic"),
    ("Bambu Lab", "Red", "#C12E1F", "PLA Basic"),
    ("Bambu Lab", "Maroon Red", "#9D2235", "PLA Basic"),
    ("Bambu Lab", "Magenta", "#EC008C", "PLA Basic"),
    ("Bambu Lab", "Hot Pink", "#F5547C", "PLA Basic"),
    ("Bambu Lab", "Pink", "#F55A74", "PLA Basic"),
    ("Bambu Lab", "Beige", "#F7E6DE", "PLA Basic"),
    ("Bambu Lab", "Yellow", "#F4EE2A", "PLA Basic"),
    ("Bambu Lab", "Sunflower Yellow", "#FEC600", "PLA Basic"),
    ("Bambu Lab", "Gold", "#E4BD68", "PLA Basic"),
    ("Bambu Lab", "Orange", "#FF6A13", "PLA Basic"),
    ("Bambu Lab", "Pumpkin Orange", "#FF9016", "PLA Basic"),
    ("Bambu Lab", "Bright Green", "#BECF00", "PLA Basic"),
    ("Bambu Lab", "Bambu Green", "#00AE42", "PLA Basic"),
    ("Bambu Lab", "Mistletoe Green", "#3F8E43", "PLA Basic"),
    ("Bambu Lab", "Turquoise", "#00B1B7", "PLA Basic"),
    ("Bambu Lab", "Cyan", "#0086D6", "PLA Basic"),
    ("Bambu Lab", "Blue", "#0A2989", "PLA Basic"),
    ("Bambu Lab", "Blue Grey", "#5B6579", "PLA Basic"),
    ("Bambu Lab", "Cobalt Blue", "#0056B8", "PLA Basic"),
    ("Bambu Lab", "Purple", "#5E43B7", "PLA Basic"),
    ("Bambu Lab", "Indigo Purple", "#482960", "PLA Basic"),
    ("Bambu Lab", "Brown", "#9D432C", "PLA Basic"),
    ("Bambu Lab", "Cocoa Brown", "#6F5034", "PLA Basic"),
    ("Bambu Lab", "Bronze", "#847D48", "PLA Basic"),
    # Bambu Lab PLA Matte (from official hex code PDF)
    ("Bambu Lab", "Ivory White", "#FFFFFF", "PLA Matte"),
    ("Bambu Lab", "Bone White", "#CBC6B8", "PLA Matte"),
    ("Bambu Lab", "Desert Tan", "#E8DBB7", "PLA Matte"),
    ("Bambu Lab", "Latte Brown", "#D3B7A7", "PLA Matte"),
    ("Bambu Lab", "Caramel", "#AE835B", "PLA Matte"),
    ("Bambu Lab", "Terracotta", "#B15533", "PLA Matte"),
    ("Bambu Lab", "Dark Brown", "#7D6556", "PLA Matte"),
    ("Bambu Lab", "Dark Chocolate", "#4D3324", "PLA Matte"),
    ("Bambu Lab", "Lilac Purple", "#AE96D4", "PLA Matte"),
    ("Bambu Lab", "Sakura Pink", "#E8AFCF", "PLA Matte"),
    ("Bambu Lab", "Mandarin Orange", "#F99963", "PLA Matte"),
    ("Bambu Lab", "Lemon Yellow", "#F7D959", "PLA Matte"),
    ("Bambu Lab", "Plum", "#950051", "PLA Matte"),
    ("Bambu Lab", "Scarlet Red", "#DE4343", "PLA Matte"),
    ("Bambu Lab", "Dark Red", "#BB3D43", "PLA Matte"),
    ("Bambu Lab", "Dark Green", "#68724D", "PLA Matte"),
    ("Bambu Lab", "Grass Green", "#61C680", "PLA Matte"),
    ("Bambu Lab", "Apple Green", "#C2E189", "PLA Matte"),
    ("Bambu Lab", "Ice Blue", "#A3D8E1", "PLA Matte"),
    ("Bambu Lab", "Sky Blue", "#56B7E6", "PLA Matte"),
    ("Bambu Lab", "Marine Blue", "#0078BF", "PLA Matte"),
    ("Bambu Lab", "Dark Blue", "#042F56", "PLA Matte"),
    ("Bambu Lab", "Ash Gray", "#9B9EA0", "PLA Matte"),
    ("Bambu Lab", "Nardo Gray", "#757575", "PLA Matte"),
    ("Bambu Lab", "Charcoal", "#000000", "PLA Matte"),
    # Bambu Lab PLA Silk+ (from store page)
    ("Bambu Lab", "Gold", "#F4A925", "PLA Silk"),
    ("Bambu Lab", "Silver", "#C8C8C8", "PLA Silk"),
    ("Bambu Lab", "Titan Gray", "#5F6367", "PLA Silk"),
    ("Bambu Lab", "Blue", "#008BDA", "PLA Silk"),
    ("Bambu Lab", "Purple", "#8671CB", "PLA Silk"),
    ("Bambu Lab", "Candy Red", "#D02727", "PLA Silk"),
    ("Bambu Lab", "Candy Green", "#018814", "PLA Silk"),
    ("Bambu Lab", "Rose Gold", "#BA9594", "PLA Silk"),
    ("Bambu Lab", "Baby Blue", "#A8C6EE", "PLA Silk"),
    ("Bambu Lab", "Pink", "#F7ADA6", "PLA Silk"),
    ("Bambu Lab", "Mint", "#96DCB9", "PLA Silk"),
    ("Bambu Lab", "Champagne", "#F3CFB2", "PLA Silk"),
    ("Bambu Lab", "White", "#FFFFFF", "PLA Silk"),
    # Bambu Lab PLA Sparkle (from store page)
    ("Bambu Lab", "Classic Gold Sparkle", "#CEA629", "PLA Sparkle"),
    ("Bambu Lab", "Slate Gray Sparkle", "#8E9089", "PLA Sparkle"),
    ("Bambu Lab", "Crimson Red Sparkle", "#792B36", "PLA Sparkle"),
    ("Bambu Lab", "Royal Purple Sparkle", "#483D8B", "PLA Sparkle"),
    ("Bambu Lab", "Alpine Green Sparkle", "#3F5443", "PLA Sparkle"),
    ("Bambu Lab", "Onyx Black Sparkle", "#2D2B28", "PLA Sparkle"),
    # Bambu Lab PLA Translucent (from official hex code PDF)
    ("Bambu Lab", "Teal", "#009FA1", "PLA Translucent"),
    ("Bambu Lab", "Light Jade", "#96D8AF", "PLA Translucent"),
    ("Bambu Lab", "Blue", "#0047BB", "PLA Translucent"),
    ("Bambu Lab", "Mellow Yellow", "#F5DBAB", "PLA Translucent"),
    ("Bambu Lab", "Purple", "#8344B0", "PLA Translucent"),
    ("Bambu Lab", "Cherry Pink", "#F5B6CD", "PLA Translucent"),
    ("Bambu Lab", "Orange", "#F74E02", "PLA Translucent"),
    ("Bambu Lab", "Ice Blue", "#B8CDE9", "PLA Translucent"),
    ("Bambu Lab", "Red", "#B50011", "PLA Translucent"),
    ("Bambu Lab", "Lavender", "#B8ACD6", "PLA Translucent"),
    # Bambu Lab PLA Glow (from store page)
    ("Bambu Lab", "Glow Green", "#A1FFAC", "PLA Glow"),
    ("Bambu Lab", "Glow Yellow", "#F8FF80", "PLA Glow"),
    ("Bambu Lab", "Glow Pink", "#F17B8F", "PLA Glow"),
    ("Bambu Lab", "Glow Blue", "#7AC0E9", "PLA Glow"),
    ("Bambu Lab", "Glow Orange", "#FF9D5B", "PLA Glow"),
    # Bambu Lab PLA Galaxy (from store page)
    ("Bambu Lab", "Brown", "#684A43", "PLA Galaxy"),
    ("Bambu Lab", "Green", "#3B665E", "PLA Galaxy"),
    ("Bambu Lab", "Nebulae", "#424379", "PLA Galaxy"),
    ("Bambu Lab", "Purple", "#594177", "PLA Galaxy"),
    # Bambu Lab PLA Metal (from store page)
    ("Bambu Lab", "Iridium Gold Metallic", "#B39B84", "PLA Metal"),
    ("Bambu Lab", "Copper Brown Metallic", "#AA6443", "PLA Metal"),
    ("Bambu Lab", "Oxide Green Metallic", "#1D7C6A", "PLA Metal"),
    ("Bambu Lab", "Cobalt Blue Metallic", "#39699E", "PLA Metal"),
    ("Bambu Lab", "Iron Gray Metallic", "#43403D", "PLA Metal"),
    # Bambu Lab PLA Marble (from store page)
    ("Bambu Lab", "White Marble", "#F7F3F0", "PLA Marble"),
    ("Bambu Lab", "Red Granite", "#AD4E38", "PLA Marble"),
    # Bambu Lab PLA Wood (from store page)
    ("Bambu Lab", "Black Walnut", "#4F3F24", "PLA Wood"),
    ("Bambu Lab", "Rosewood", "#4C241C", "PLA Wood"),
    ("Bambu Lab", "Clay Brown", "#995F11", "PLA Wood"),
    ("Bambu Lab", "Classic Birch", "#918669", "PLA Wood"),
    ("Bambu Lab", "White Oak", "#D6CCA3", "PLA Wood"),
    ("Bambu Lab", "Ochre Yellow", "#C98935", "PLA Wood"),
    # Bambu Lab PLA Tough+ (from official hex code PDF)
    ("Bambu Lab", "White", "#FFFFFF", "PLA Tough"),
    ("Bambu Lab", "Gray", "#AFB1AE", "PLA Tough"),
    ("Bambu Lab", "Black", "#000000", "PLA Tough"),
    ("Bambu Lab", "Silver", "#959698", "PLA Tough"),
    ("Bambu Lab", "Yellow", "#F4D53F", "PLA Tough"),
    ("Bambu Lab", "Cyan", "#009BD8", "PLA Tough"),
    ("Bambu Lab", "Orange", "#DC3A27", "PLA Tough"),
    # Bambu Lab PLA-CF (from official hex code PDF)
    ("Bambu Lab", "Burgundy Red", "#951E23", "PLA-CF"),
    ("Bambu Lab", "Iris Purple", "#69398E", "PLA-CF"),
    ("Bambu Lab", "Matcha Green", "#5C9748", "PLA-CF"),
    ("Bambu Lab", "Jeans Blue", "#6E88BC", "PLA-CF"),
    ("Bambu Lab", "Royal Blue", "#2842AD", "PLA-CF"),
    ("Bambu Lab", "Lava Gray", "#4D5054", "PLA-CF"),
    ("Bambu Lab", "Black", "#000000", "PLA-CF"),
    # Bambu Lab ABS (from official hex code PDF)
    ("Bambu Lab", "White", "#FFFFFF", "ABS"),
    ("Bambu Lab", "Desert Tan", "#E8DBB7", "ABS"),
    ("Bambu Lab", "Olive", "#789D4A", "ABS"),
    ("Bambu Lab", "Azure", "#489FDF", "ABS"),
    ("Bambu Lab", "Navy Blue", "#0C2340", "ABS"),
    ("Bambu Lab", "Blue", "#0A2CA5", "ABS"),
    ("Bambu Lab", "Tangerine Yellow", "#FFC72C", "ABS"),
    ("Bambu Lab", "Orange", "#FF6A13", "ABS"),
    ("Bambu Lab", "Red", "#D32941", "ABS"),
    ("Bambu Lab", "Purple", "#AF1685", "ABS"),
    ("Bambu Lab", "Silver", "#87909A", "ABS"),
    ("Bambu Lab", "Black", "#000000", "ABS"),
    # Bambu Lab ASA (from store page)
    ("Bambu Lab", "White", "#FFFAF2", "ASA"),
    ("Bambu Lab", "Gray", "#8A949E", "ASA"),
    ("Bambu Lab", "Red", "#E02928", "ASA"),
    ("Bambu Lab", "Green", "#00A6A0", "ASA"),
    ("Bambu Lab", "Blue", "#2140B4", "ASA"),
    ("Bambu Lab", "Black", "#000000", "ASA"),
    # Bambu Lab PETG HF (from store page)
    ("Bambu Lab", "Yellow", "#FFD00B", "PETG HF"),
    ("Bambu Lab", "Orange", "#F75403", "PETG HF"),
    ("Bambu Lab", "Green", "#00AE42", "PETG HF"),
    ("Bambu Lab", "Red", "#EB3A3A", "PETG HF"),
    ("Bambu Lab", "Blue", "#002E96", "PETG HF"),
    ("Bambu Lab", "Black", "#000000", "PETG HF"),
    ("Bambu Lab", "White", "#FFFFFF", "PETG HF"),
    ("Bambu Lab", "Cream", "#F9DFB9", "PETG HF"),
    ("Bambu Lab", "Lime Green", "#6EE53C", "PETG HF"),
    ("Bambu Lab", "Forest Green", "#39541A", "PETG HF"),
    ("Bambu Lab", "Lake Blue", "#1F79E5", "PETG HF"),
    ("Bambu Lab", "Peanut Brown", "#875718", "PETG HF"),
    ("Bambu Lab", "Gray", "#ADB1B2", "PETG HF"),
    ("Bambu Lab", "Dark Gray", "#515151", "PETG HF"),
    # Bambu Lab PETG Translucent (from store page)
    ("Bambu Lab", "Translucent Gray", "#8E8E8E", "PETG Translucent"),
    ("Bambu Lab", "Translucent Light Blue", "#61B0FF", "PETG Translucent"),
    ("Bambu Lab", "Translucent Olive", "#748C45", "PETG Translucent"),
    ("Bambu Lab", "Translucent Brown", "#C9A381", "PETG Translucent"),
    ("Bambu Lab", "Translucent Teal", "#77EDD7", "PETG Translucent"),
    ("Bambu Lab", "Translucent Orange", "#FF911A", "PETG Translucent"),
    ("Bambu Lab", "Translucent Purple", "#D6ABFF", "PETG Translucent"),
    ("Bambu Lab", "Translucent Pink", "#F9C1BD", "PETG Translucent"),
    # Bambu Lab PETG-CF (from official hex code PDF)
    ("Bambu Lab", "Brick Red", "#9F332A", "PETG-CF"),
    ("Bambu Lab", "Violet Purple", "#583061", "PETG-CF"),
    ("Bambu Lab", "Indigo Blue", "#324585", "PETG-CF"),
    ("Bambu Lab", "Malachite Green", "#16B08E", "PETG-CF"),
    ("Bambu Lab", "Black", "#000000", "PETG-CF"),
    ("Bambu Lab", "Titan Gray", "#565656", "PETG-CF"),
    # Bambu Lab TPU 95A HF (from store page)
    ("Bambu Lab", "White", "#FFFFFF", "TPU 95A"),
    ("Bambu Lab", "Yellow", "#F3E600", "TPU 95A"),
    ("Bambu Lab", "Blue", "#0072CE", "TPU 95A"),
    ("Bambu Lab", "Red", "#C8102E", "TPU 95A"),
    ("Bambu Lab", "Gray", "#898D8D", "TPU 95A"),
    ("Bambu Lab", "Black", "#101820", "TPU 95A"),
    # Bambu Lab TPU 90A (from official hex code PDF)
    ("Bambu Lab", "Black", "#000000", "TPU 90A"),
    ("Bambu Lab", "White", "#FFFFFF", "TPU 90A"),
    ("Bambu Lab", "Grape Jelly", "#D6ABFF", "TPU 90A"),
    ("Bambu Lab", "Crystal Blue", "#7EB4E1", "TPU 90A"),
    ("Bambu Lab", "Cocoa Brown", "#5C4738", "TPU 90A"),
    # Bambu Lab PAHT-CF
    ("Bambu Lab", "Black", "#1A1A1A", "PAHT-CF"),
    # Bambu Lab Support Materials
    ("Bambu Lab", "Natural", "#F5F5DC", "PLA Support"),
    ("Bambu Lab", "Natural", "#F5F5DC", "PVA Support"),
    # Polymaker PolyTerra PLA
    ("Polymaker", "Cotton White", "#F5F5F5", "PolyTerra PLA"),
    ("Polymaker", "Charcoal Black", "#2B2B2B", "PolyTerra PLA"),
    ("Polymaker", "Marble White", "#E8E8E8", "PolyTerra PLA"),
    ("Polymaker", "Fossil Grey", "#6B6B6B", "PolyTerra PLA"),
    ("Polymaker", "Shadow Black", "#1A1A1A", "PolyTerra PLA"),
    ("Polymaker", "Army Red", "#8B0000", "PolyTerra PLA"),
    ("Polymaker", "Lava Red", "#CF1020", "PolyTerra PLA"),
    ("Polymaker", "Sakura Pink", "#FFB7C5", "PolyTerra PLA"),
    ("Polymaker", "Rose", "#FF007F", "PolyTerra PLA"),
    ("Polymaker", "Peach", "#FFCBA4", "PolyTerra PLA"),
    ("Polymaker", "Banana", "#FFE135", "PolyTerra PLA"),
    ("Polymaker", "Savannah Yellow", "#F4C430", "PolyTerra PLA"),
    ("Polymaker", "Sunrise Orange", "#FF6600", "PolyTerra PLA"),
    ("Polymaker", "Muted Green", "#4F7942", "PolyTerra PLA"),
    ("Polymaker", "Forest Green", "#228B22", "PolyTerra PLA"),
    ("Polymaker", "Mint", "#98FF98", "PolyTerra PLA"),
    ("Polymaker", "Lavender Purple", "#B57EDC", "PolyTerra PLA"),
    ("Polymaker", "Sapphire Blue", "#0F52BA", "PolyTerra PLA"),
    ("Polymaker", "Ice", "#D6ECEF", "PolyTerra PLA"),
    # Prusament PLA
    ("Prusament", "Jet Black", "#1A1A1A", "PLA"),
    ("Prusament", "Galaxy Black", "#1F1F1F", "PLA"),
    ("Prusament", "Pristine White", "#FFFFFF", "PLA"),
    ("Prusament", "Gentleman's Grey", "#5A5A5A", "PLA"),
    ("Prusament", "Lipstick Red", "#C21E1E", "PLA"),
    ("Prusament", "Orange", "#FF6600", "PLA"),
    ("Prusament", "Pineapple Yellow", "#FFD700", "PLA"),
    ("Prusament", "Jungle Green", "#29AB87", "PLA"),
    ("Prusament", "Azure Blue", "#007FFF", "PLA"),
    ("Prusament", "Royal Blue", "#4169E1", "PLA"),
    ("Prusament", "Mystic Purple", "#7B68EE", "PLA"),
    # eSUN PLA+ (from FilamentColors.xyz measured swatches)
    ("eSUN", "Beige", "#ECCAB0", "PLA+"),
    ("eSUN", "Black", "#373838", "PLA+"),
    ("eSUN", "Blue", "#054795", "PLA+"),
    ("eSUN", "Bone White", "#C2BAA7", "PLA+"),
    ("eSUN", "Brown", "#6F513C", "PLA+"),
    ("eSUN", "Cool White", "#E1E4E5", "PLA+"),
    ("eSUN", "Dark Blue", "#2F314D", "PLA+"),
    ("eSUN", "Fire Engine Red", "#91202B", "PLA+"),
    ("eSUN", "Gold", "#C99B26", "PLA+"),
    ("eSUN", "Gray", "#697480", "PLA+"),
    ("eSUN", "Green", "#015E58", "PLA+"),
    ("eSUN", "Grey", "#5F6574", "PLA+"),
    ("eSUN", "Light Blue", "#48BFD5", "PLA+"),
    ("eSUN", "Light Brown", "#A27556", "PLA+"),
    ("eSUN", "Luminous Blue", "#C8CAC8", "PLA+"),
    ("eSUN", "Magenta", "#DA3B6C", "PLA+"),
    ("eSUN", "Olive Green", "#555B45", "PLA+"),
    ("eSUN", "Orange", "#EF7749", "PLA+"),
    ("eSUN", "Peak Green", "#A1DA7C", "PLA+"),
    ("eSUN", "Pink", "#E78397", "PLA+"),
    ("eSUN", "Purple", "#8350A4", "PLA+"),
    ("eSUN", "Red", "#C4402A", "PLA+"),
    ("eSUN", "Silver", "#8B8889", "PLA+"),
    ("eSUN", "Skin", "#E3C7AF", "PLA+"),
    ("eSUN", "White", "#E1E9E9", "PLA+"),
    ("eSUN", "Yellow", "#FBCE2B", "PLA+"),
    # eSUN Pro PLA+
    ("eSUN", "Blue", "#065AA1", "Pro PLA+"),
    # eSUN PLA
    ("eSUN", "Glow in the Dark", "#C5C2AB", "PLA"),
    ("eSUN", "Marble White", "#B5BCC0", "PLA"),
    ("eSUN", "Natural Wood", "#EBCFA6", "PLA"),
    ("eSUN", "Pine Green", "#375C49", "PLA"),
    ("eSUN", "UV Change Purple", "#CABBA9", "PLA"),
    ("eSUN", "eTwinkling Blue", "#115CAF", "PLA"),
    ("eSUN", "eStars Galaxy Black", "#403936", "PLA"),
    # eSUN PLA Silk
    ("eSUN", "Silk Blue", "#2275AA", "PLA Silk"),
    ("eSUN", "Silk Bronze", "#829172", "PLA Silk"),
    ("eSUN", "Silk Copper", "#AE6B2F", "PLA Silk"),
    ("eSUN", "Silk Cyan", "#34A7CF", "PLA Silk"),
    ("eSUN", "Silk Dark Yellow", "#D4A62E", "PLA Silk"),
    ("eSUN", "Silk Gold", "#C48E2F", "PLA Silk"),
    ("eSUN", "Silk Green", "#7FCB43", "PLA Silk"),
    ("eSUN", "Silk Jacinth", "#DA8061", "PLA Silk"),
    ("eSUN", "Silk Lime", "#C1D762", "PLA Silk"),
    ("eSUN", "Silk Magic Green Blue", "#508669", "PLA Silk"),
    ("eSUN", "Silk Purple", "#905295", "PLA Silk"),
    ("eSUN", "Silk Red", "#C94830", "PLA Silk"),
    ("eSUN", "Silk Rose Gold", "#C7886B", "PLA Silk"),
    ("eSUN", "Silk Silver", "#B5C1C5", "PLA Silk"),
    ("eSUN", "Silk Violet", "#B93CA1", "PLA Silk"),
    ("eSUN", "Silk White", "#E3E0DB", "PLA Silk"),
    ("eSUN", "Silk Yellow", "#DED74B", "PLA Silk"),
    # eSUN PLA Metal
    ("eSUN", "Bronze", "#917F57", "PLA Metal"),
    # eSUN PLA-ST
    ("eSUN", "Grey", "#626C77", "PLA-ST"),
    # eSUN PETG
    ("eSUN", "Black", "#353434", "PETG"),
    ("eSUN", "Magenta", "#E03E76", "PETG"),
    ("eSUN", "Solid Blue", "#1A6FB4", "PETG"),
    ("eSUN", "Solid Green", "#008A58", "PETG"),
    ("eSUN", "Solid Purple", "#7A4795", "PETG"),
    ("eSUN", "Solid White", "#F4F1F1", "PETG"),
    ("eSUN", "Solid Yellow", "#F0CA41", "PETG"),
    ("eSUN", "Translucent Green", "#378041", "PETG"),
    ("eSUN", "Translucent Orange", "#DD7135", "PETG"),
    ("eSUN", "White", "#E7EDED", "PETG"),
    # eSUN PETG-HS (High Speed)
    ("eSUN", "Black", "#424445", "PETG-HS"),
    ("eSUN", "Solid Blue", "#1A6FB4", "PETG-HS"),
    # eSUN ABS
    ("eSUN", "Black", "#3F3A3F", "ABS"),
    ("eSUN", "Brown", "#624741", "ABS"),
    ("eSUN", "Natural", "#D9E3DD", "ABS"),
    ("eSUN", "Pine Green", "#3C694E", "ABS"),
    ("eSUN", "Pink", "#E86477", "ABS"),
    ("eSUN", "Red", "#A74237", "ABS"),
    ("eSUN", "Silver", "#838080", "ABS"),
    # eSUN ABS+
    ("eSUN", "Gray", "#616777", "ABS+"),
    ("eSUN", "Green", "#018068", "ABS+"),
    ("eSUN", "Natural", "#E4DEC9", "ABS+"),
    ("eSUN", "Orange", "#EE7845", "ABS+"),
    ("eSUN", "Silver", "#7F807E", "ABS+"),
    ("eSUN", "White", "#E1E1DF", "ABS+"),
    ("eSUN", "Yellow", "#D3BC0F", "ABS+"),
    # Hatchbox PLA
    ("Hatchbox", "White", "#FFFFFF", "PLA"),
    ("Hatchbox", "Black", "#000000", "PLA"),
    ("Hatchbox", "Gray", "#808080", "PLA"),
    ("Hatchbox", "Red", "#FF0000", "PLA"),
    ("Hatchbox", "Blue", "#0000FF", "PLA"),
    ("Hatchbox", "Green", "#00FF00", "PLA"),
    ("Hatchbox", "Yellow", "#FFFF00", "PLA"),
    ("Hatchbox", "Orange", "#FFA500", "PLA"),
    ("Hatchbox", "Purple", "#800080", "PLA"),
    ("Hatchbox", "Pink", "#FFC0CB", "PLA"),
    ("Hatchbox", "True Blue", "#0073CF", "PLA"),
    ("Hatchbox", "True Green", "#008000", "PLA"),
    # Overture PLA (from FilamentColors.xyz measured swatches)
    ("Overture", "Black", "#2B292E", "PLA"),
    ("Overture", "Blue", "#034070", "PLA"),
    ("Overture", "Cement Gray", "#48494A", "PLA"),
    ("Overture", "Dark Blue", "#124775", "PLA"),
    ("Overture", "Fresh Red", "#C01F1D", "PLA"),
    ("Overture", "Gray Blue", "#6D8790", "PLA"),
    ("Overture", "Green", "#318C49", "PLA"),
    ("Overture", "Highlight Yellow", "#FBF93C", "PLA"),
    ("Overture", "Light Blue", "#7CC4D5", "PLA"),
    ("Overture", "Light Gray", "#8F9694", "PLA"),
    ("Overture", "Neon Green Air", "#C5ED33", "PLA"),
    ("Overture", "Olive Green", "#8F843D", "PLA"),
    ("Overture", "Pink", "#DC99B4", "PLA"),
    ("Overture", "Red", "#C9341A", "PLA"),
    ("Overture", "Royal Gold", "#C58F31", "PLA"),
    ("Overture", "Space Grey", "#797779", "PLA"),
    ("Overture", "White", "#E7EBE3", "PLA"),
    # Overture PLA Matte
    ("Overture", "Black", "#3F3E41", "PLA Matte"),
    ("Overture", "Blue", "#277EAB", "PLA Matte"),
    ("Overture", "Brick Red", "#AE4848", "PLA Matte"),
    ("Overture", "Green", "#5EAE73", "PLA Matte"),
    ("Overture", "Light Grey", "#919598", "PLA Matte"),
    ("Overture", "Light Brown", "#BF9C80", "PLA Matte"),
    ("Overture", "Light Green", "#A1C1A5", "PLA Matte"),
    ("Overture", "Olive Green", "#B59837", "PLA Matte"),
    ("Overture", "Orange", "#F59752", "PLA Matte"),
    ("Overture", "Pink", "#EBBDCE", "PLA Matte"),
    ("Overture", "Purple", "#978DC5", "PLA Matte"),
    ("Overture", "White", "#E1E4DD", "PLA Matte"),
    ("Overture", "Yellow", "#FFD359", "PLA Matte"),
    # Overture PLA Pro
    ("Overture", "Digital Blue", "#008FBE", "PLA Pro"),
    ("Overture", "Light Blue", "#68C8DB", "PLA Pro"),
    ("Overture", "Orange", "#F27C1B", "PLA Pro"),
    ("Overture", "Purple", "#7B5DB0", "PLA Pro"),
    ("Overture", "Red", "#E62F18", "PLA Pro"),
    ("Overture", "Yellow", "#DFB233", "PLA Pro"),
    # Overture PETG
    ("Overture", "Black", "#2F2821", "PETG"),
    ("Overture", "Blue", "#225291", "PETG"),
    ("Overture", "Clear", "#BEC3C5", "PETG"),
    ("Overture", "Pink", "#E0A1BA", "PETG"),
    ("Overture", "Purple", "#67518F", "PETG"),
    ("Overture", "Rock White", "#C2C8C9", "PETG"),
    ("Overture", "Red", "#AB291B", "PETG"),
    ("Overture", "Space Grey", "#80817E", "PETG"),
    ("Overture", "Translucent Blue", "#38487B", "PETG"),
    ("Overture", "White", "#E7E9E7", "PETG"),
    ("Overture", "Yellow", "#E6B93C", "PETG"),
    # Overture ABS
    ("Overture", "Diamond Gray", "#5D5F5F", "ABS"),
    ("Overture", "Diamond Purple", "#6B649D", "ABS"),
    # Overture Silk PLA
    ("Overture", "Gold", "#CA9B52", "Silk PLA"),
    ("Overture", "Neon Green", "#C2D74D", "Silk PLA"),
    ("Overture", "Copper", "#B27052", "Silk PLA"),
    # Overture Glow PLA
    ("Overture", "Glow Blue", "#4EA2AA", "Glow PLA"),
    ("Overture", "Glow Orange", "#C2895E", "Glow PLA"),
    ("Overture", "Glow Red", "#C27B7D", "Glow PLA"),
    ("Overture", "Glow Yellow", "#E3F079", "Glow PLA"),
    # Sunlu PLA (from FilamentColors.xyz measured swatches)
    ("Sunlu", "Black", "#3C3C3C", "PLA"),
    ("Sunlu", "Blue", "#006AB8", "PLA"),
    ("Sunlu", "Cherry Red", "#EA4A5D", "PLA"),
    ("Sunlu", "Glow in the Dark", "#CBCAB8", "PLA"),
    ("Sunlu", "Green Mint", "#4CCB9A", "PLA"),
    ("Sunlu", "Grey", "#6B6E6E", "PLA"),
    ("Sunlu", "Orange", "#E77932", "PLA"),
    ("Sunlu", "Red", "#AC3637", "PLA"),
    ("Sunlu", "Sky Blue", "#0CB7CC", "PLA"),
    ("Sunlu", "Sunny Orange", "#FF7235", "PLA"),
    ("Sunlu", "Transparent", "#C8C7BF", "PLA"),
    ("Sunlu", "Transparent Orange", "#DB7F42", "PLA"),
    ("Sunlu", "White", "#DEDFD9", "PLA"),
    ("Sunlu", "Wood", "#D5BA95", "PLA"),
    # Sunlu PLA Silk
    ("Sunlu", "Silk Black", "#737272", "PLA Silk"),
    ("Sunlu", "Silk Green", "#34C0A5", "PLA Silk"),
    ("Sunlu", "Silk Red", "#CD5C62", "PLA Silk"),
    ("Sunlu", "Silky Silver", "#C6CBD0", "PLA Silk"),
    # Sunlu PLA Meta
    ("Sunlu", "Blue", "#00B2CC", "PLA Meta"),
    ("Sunlu", "Mint Green", "#03A490", "PLA Meta"),
    ("Sunlu", "Sakura Pink", "#F5B5C2", "PLA Meta"),
    ("Sunlu", "Taro Purple", "#A69ED0", "PLA Meta"),
    # Sunlu PLA+
    ("Sunlu", "Beige", "#DDBCAC", "PLA+"),
    ("Sunlu", "Black", "#3A3B3B", "PLA+"),
    ("Sunlu", "Blue", "#0063A0", "PLA+"),
    ("Sunlu", "Green", "#4EE349", "PLA+"),
    ("Sunlu", "Light Gold", "#D3943D", "PLA+"),
    ("Sunlu", "Mint Green", "#00B39A", "PLA+"),
    ("Sunlu", "Orange", "#ED7432", "PLA+"),
    ("Sunlu", "Pure Yellow", "#FFBD2C", "PLA+"),
    ("Sunlu", "Purple", "#8887C5", "PLA+"),
    ("Sunlu", "Red", "#B34044", "PLA+"),
    ("Sunlu", "Silk Blue", "#33ACD4", "PLA+"),
    ("Sunlu", "Silk Brass", "#F1A050", "PLA+"),
    ("Sunlu", "Silk Pink", "#FFCAD9", "PLA+"),
    ("Sunlu", "Silk White", "#EEEFE7", "PLA+"),
    ("Sunlu", "Skin", "#F7BEA1", "PLA+"),
    ("Sunlu", "White", "#E6E6E2", "PLA+"),
    # Sunlu PETG
    ("Sunlu", "Black", "#3F4141", "PETG"),
    ("Sunlu", "Blue", "#0068AB", "PETG"),
    ("Sunlu", "Green", "#67DB25", "PETG"),
    ("Sunlu", "Olive Green", "#707D63", "PETG"),
    ("Sunlu", "Transparent", "#BAB9B4", "PETG"),
    ("Sunlu", "White", "#DBDDD9", "PETG"),
    # Sunlu ABS
    ("Sunlu", "Black", "#404142", "ABS"),
    # Creality Hyper PLA (from FilamentColors.xyz measured swatches)
    ("Creality", "Black", "#282C2C", "Hyper PLA"),
    ("Creality", "Blue", "#0881BE", "Hyper PLA"),
    ("Creality", "Grey", "#7A7C7C", "Hyper PLA"),
    ("Creality", "Purple", "#B0347E", "Hyper PLA"),
    ("Creality", "Red", "#C32E2F", "Hyper PLA"),
    ("Creality", "White", "#DEE4E1", "Hyper PLA"),
    # Creality Hyper PLA-CF
    ("Creality", "Black", "#322F2D", "Hyper PLA-CF"),
    # Creality PLA
    ("Creality", "Gray", "#8F9395", "PLA"),
    ("Creality", "White", "#E1DFD0", "PLA"),
    # Creality PETG
    ("Creality", "White", "#E3E5E1", "PETG"),
    # Creality Silk PLA
    ("Creality", "Blue-Green", "#479B7D", "Silk PLA"),
    # Elegoo PLA (from FilamentColors.xyz measured swatches)
    ("Elegoo", "Black", "#282929", "PLA"),
    ("Elegoo", "Clear", "#BEBBBF", "PLA"),
    ("Elegoo", "Galaxy Black", "#32464E", "PLA"),
    ("Elegoo", "Galaxy Purple", "#3A2F6F", "PLA"),
    ("Elegoo", "Grey", "#B5B7B7", "PLA"),
    ("Elegoo", "Peacock Blue", "#21606B", "PLA"),
    ("Elegoo", "Sky Blue", "#46C8D4", "PLA"),
    # Elegoo PLA+
    ("Elegoo", "Black", "#343132", "PLA+"),
    ("Elegoo", "Orange", "#CC6A2F", "PLA+"),
    ("Elegoo", "Purple", "#6E45A7", "PLA+"),
    # Elegoo Silk PLA
    ("Elegoo", "Coral Pink", "#DB6E6D", "Silk PLA"),
    ("Elegoo", "Gold", "#E2AC00", "Silk PLA"),
    ("Elegoo", "Silver", "#93969B", "Silk PLA"),
    # Jayo PLA+ (from FilamentColors.xyz measured swatches)
    ("Jayo", "Black", "#2F2E2D", "PLA+"),
    ("Jayo", "Cherry Red", "#C43536", "PLA+"),
    ("Jayo", "White", "#D9E0E7", "PLA+"),
    # Inland PLA (from FilamentColors.xyz measured swatches)
    ("Inland", "Black", "#27272C", "PLA"),
    ("Inland", "Blue", "#044482", "PLA"),
    ("Inland", "Coral", "#C16062", "PLA"),
    ("Inland", "Egyptian Blue", "#075AAC", "PLA"),
    ("Inland", "Gold", "#D7B536", "PLA"),
    ("Inland", "Green", "#407166", "PLA"),
    ("Inland", "Grey", "#6F7983", "PLA"),
    ("Inland", "Light Blue", "#3CA4B8", "PLA"),
    ("Inland", "Military Green", "#5B6D37", "PLA"),
    ("Inland", "Pink", "#FC97AF", "PLA"),
    ("Inland", "Red", "#C43220", "PLA"),
    ("Inland", "Silver", "#8A8F92", "PLA"),
    ("Inland", "True Red", "#B13137", "PLA"),
    ("Inland", "White", "#E0E3E3", "PLA"),
    ("Inland", "Wood", "#DEB98F", "PLA"),
    # Inland PLA+
    ("Inland", "Black", "#2B272B", "PLA+"),
    ("Inland", "Blue", "#054990", "PLA+"),
    ("Inland", "Bone White", "#ABA18F", "PLA+"),
    ("Inland", "Dark Blue", "#2C3353", "PLA+"),
    ("Inland", "Light Blue", "#079FBF", "PLA+"),
    ("Inland", "Magenta", "#DE2B60", "PLA+"),
    ("Inland", "Orange", "#FB8B5A", "PLA+"),
    ("Inland", "Pink", "#F291A4", "PLA+"),
    ("Inland", "Purple", "#744FA0", "PLA+"),
    ("Inland", "Silver", "#868A8B", "PLA+"),
    ("Inland", "White", "#E3E5E5", "PLA+"),
    ("Inland", "Yellow", "#F8D008", "PLA+"),
    # Inland PETG
    ("Inland", "Blue", "#084480", "PETG"),
    ("Inland", "Green", "#2B783E", "PETG"),
    ("Inland", "Magenta", "#E14170", "PETG"),
    ("Inland", "Transparent", "#D1D6D1", "PETG"),
    ("Inland", "True Red", "#97392B", "PETG"),
    # Inland ABS
    ("Inland", "Grey", "#8A97A2", "ABS"),
    ("Inland", "Light Blue", "#6CBECF", "ABS"),
    ("Inland", "Orange", "#E8712F", "ABS"),
    # Inland Tough PLA
    ("Inland", "Light Gray", "#8D9497", "Tough PLA"),
    ("Inland", "Yellow", "#FFBB3F", "Tough PLA"),
    # Eryone PLA (from FilamentColors.xyz measured swatches)
    ("Eryone", "Galaxy Purple", "#60617B", "PLA"),
    ("Eryone", "Galaxy Red", "#8E3332", "PLA"),
    ("Eryone", "Glow in the Dark", "#C2C1AF", "PLA"),
    ("Eryone", "Ivory White", "#DCDCD3", "PLA"),
    ("Eryone", "Silk Blue", "#64A9D3", "PLA"),
    ("Eryone", "Silk Copper", "#B36A50", "PLA"),
    ("Eryone", "Silk Gold", "#D5983D", "PLA"),
    ("Eryone", "Silk Gold Copper", "#D69366", "PLA"),
    ("Eryone", "Silk Gold Silver", "#ABA787", "PLA"),
    ("Eryone", "Ultra Silk Black", "#5B6264", "PLA"),
    ("Eryone", "Ultra Silk Copper", "#B46A4D", "PLA"),
    ("Eryone", "Ultra Silk Silver", "#999BA5", "PLA"),
    # Eryone PLA+
    ("Eryone", "Army Green", "#5D644D", "PLA+"),
    # Eryone ASA
    ("Eryone", "Black", "#414446", "ASA"),
    # Eryone PLA Wood
    ("Eryone", "Light Wood", "#A5886E", "PLA Wood"),
    # ColorFabb PLA (from FilamentColors.xyz measured swatches)
    ("ColorFabb", "Stonefill Light Gray", "#A9B2B7", "PLA"),
    ("ColorFabb", "WoodFill", "#B89775", "PLA"),
    # ColorFabb PLA/PHA
    ("ColorFabb", "CopperFill", "#9D7465", "PLA/PHA"),
    ("ColorFabb", "CorkFill", "#7F6150", "PLA/PHA"),
    ("ColorFabb", "Natural", "#CFCFC2", "PLA/PHA"),
    # ColorFabb XT
    ("ColorFabb", "Light Gray", "#BFC5BE", "XT"),
    ("ColorFabb", "Black", "#3B3635", "XT"),
    # Fillamentum PLA Extrafill (from FilamentColors.xyz measured swatches)
    ("Fillamentum", "Baby Blue", "#B9D7DC", "PLA Extrafill"),
    ("Fillamentum", "Chocolate Brown", "#5B4A45", "PLA Extrafill"),
    ("Fillamentum", "Cobalt Blue", "#333D5C", "PLA Extrafill"),
    ("Fillamentum", "Crystal Clear Smaragd Green", "#028D77", "PLA Extrafill"),
    ("Fillamentum", "Everybody's Magenta", "#E1347D", "PLA Extrafill"),
    ("Fillamentum", "Gold Happens", "#BC994D", "PLA Extrafill"),
    ("Fillamentum", "Mukha", "#A88866", "PLA Extrafill"),
    ("Fillamentum", "Pearl Night Blue", "#045589", "PLA Extrafill"),
    ("Fillamentum", "Pearl Ruby Red", "#791F2A", "PLA Extrafill"),
    ("Fillamentum", "Rapunzel Silver", "#AFAFB0", "PLA Extrafill"),
    ("Fillamentum", "Vertigo Cherry", "#752F38", "PLA Extrafill"),
    ("Fillamentum", "Vertigo Galaxy", "#333928", "PLA Extrafill"),
    ("Fillamentum", "Vertigo Grey", "#5A5963", "PLA Extrafill"),
    ("Fillamentum", "Vertigo Starlight", "#343A4F", "PLA Extrafill"),
    ("Fillamentum", "Wizard's Voodoo", "#3F465E", "PLA Extrafill"),
    # Fillamentum PLA (Crystal Clear / Timberfill / Vertigo lines)
    ("Fillamentum", "Crystal Clear", "#EBECF2", "PLA"),
    ("Fillamentum", "Crystal Clear Amethyst Purple", "#9F99BC", "PLA"),
    ("Fillamentum", "Crystal Clear Iceland Blue", "#82BBCD", "PLA"),
    ("Fillamentum", "Crystal Clear Tangerine Orange", "#ECD082", "PLA"),
    ("Fillamentum", "Lilac", "#A99FCF", "PLA"),
    ("Fillamentum", "Timberfill Cinnamon", "#AC7C67", "PLA"),
    ("Fillamentum", "Timberfill Rosewood", "#6A564E", "PLA"),
    ("Fillamentum", "Vertigo Jade", "#217F60", "PLA"),
    # Fillamentum ASA Extrafill
    ("Fillamentum", "Anthracite Grey", "#4B4F50", "ASA Extrafill"),
    ("Fillamentum", "Green Grass", "#678653", "ASA Extrafill"),
    ("Fillamentum", "Grey Blue", "#495965", "ASA Extrafill"),
    ("Fillamentum", "Metallic Grey", "#878A8C", "ASA Extrafill"),
    ("Fillamentum", "Sky Blue", "#0783B6", "ASA Extrafill"),
    ("Fillamentum", "Snow White", "#F3F3EF", "ASA Extrafill"),
    ("Fillamentum", "Traffic Black", "#3B3B3F", "ASA Extrafill"),
    ("Fillamentum", "Traffic White", "#E9E7DA", "ASA Extrafill"),
    ("Fillamentum", "White Aluminium", "#9CA1A2", "ASA Extrafill"),
    # Fillamentum CPE HG100
    ("Fillamentum", "Black Soul", "#292B27", "CPE HG100"),
    ("Fillamentum", "Ghost White", "#E5E8E7", "CPE HG100"),
    ("Fillamentum", "Natural", "#DCE4DF", "CPE HG100"),
    # Fillamentum Flexfill TPU 98A
    ("Fillamentum", "Blue Transparent", "#047990", "Flexfill TPU 98A"),
    ("Fillamentum", "Carrot Orange", "#EA6E21", "Flexfill TPU 98A"),
    ("Fillamentum", "Metallic Grey", "#8F8E8F", "Flexfill TPU 98A"),
    ("Fillamentum", "Pistachio Green", "#A7BE36", "Flexfill TPU 98A"),
    ("Fillamentum", "Signal Red", "#9A2222", "Flexfill TPU 98A"),
    ("Fillamentum", "Traffic Black", "#26262A", "Flexfill TPU 98A"),
    ("Fillamentum", "Vertigo Grey", "#515150", "Flexfill TPU 98A"),
    # FormFutura PLA (from FilamentColors.xyz measured swatches)
    ("FormFutura", "Basalt Grey", "#5B5F61", "PLA"),
    ("FormFutura", "Dark Blue", "#084B86", "PLA"),
    ("FormFutura", "Galaxy Champagne Gold", "#AE9D83", "PLA"),
    ("FormFutura", "Gold High Gloss", "#C89B4B", "PLA"),
    ("FormFutura", "High Gloss White", "#D0D7D8", "PLA"),
    ("FormFutura", "Magenta High Gloss", "#B94474", "PLA"),
    ("FormFutura", "Stonefil Terracotta", "#BD634C", "PLA"),
    ("FormFutura", "Yellow Green", "#7AA837", "PLA"),
    # FormFutura ePLA
    ("FormFutura", "Pure Orange", "#FA9145", "EasyFil PLA"),
    # FormFutura rPLA
    ("FormFutura", "ReForm Black", "#3A3B3B", "ReForm rPLA"),
    ("FormFutura", "ReForm White", "#F3F3EC", "ReForm rPLA"),
    # Fiberlogy PLA (from FilamentColors.xyz measured swatches)
    ("Fiberlogy", "Mineral White", "#E2D9CD", "PLA"),
    ("Fiberlogy", "Aurora", "#3C4452", "Easy PLA"),
    ("Fiberlogy", "Army Green", "#535F4F", "Impact PLA"),
    # Fiberlogy ASA
    ("Fiberlogy", "Olive Green", "#61634B", "ASA"),
    # Fiberlogy Easy PETG
    ("Fiberlogy", "White", "#F2F2EE", "Easy PETG"),
    # Fiberlogy FiberSilk
    ("Fiberlogy", "Green", "#A2D780", "FiberSilk Metallic"),
    # MatterHackers Build PLA (from FilamentColors.xyz measured swatches)
    ("MatterHackers", "Blue", "#044786", "Build PLA"),
    ("MatterHackers", "Magenta", "#CD4263", "Build PLA"),
    ("MatterHackers", "Red", "#C4351B", "Build PLA"),
    ("MatterHackers", "Shiny Gold", "#DFAC1E", "Build PLA"),
    ("MatterHackers", "Silky Copper", "#C76F35", "Build PLA"),
    ("MatterHackers", "Silky Silver", "#BDBDB8", "Build PLA"),
    ("MatterHackers", "Silky Teal", "#078EBC", "Build PLA"),
    ("MatterHackers", "Silky Yellow", "#EDB554", "Build PLA"),
    ("MatterHackers", "Yellow", "#EBC100", "Build PLA"),
    # MatterHackers PLA
    ("MatterHackers", "Gold", "#E7AC37", "PLA"),
    ("MatterHackers", "Lime Green", "#75BA52", "PLA"),
    ("MatterHackers", "Pearl White", "#D4DCDD", "PLA"),
    ("MatterHackers", "Red", "#E54931", "PLA"),
    # MatterHackers Pro PLA
    ("MatterHackers", "Electric Pink", "#F35886", "Pro PLA"),
    ("MatterHackers", "Jet Gray", "#474B4C", "Pro PLA"),
    # MatterHackers PETG
    ("MatterHackers", "Clear", "#D5DDDA", "PETG"),
    ("MatterHackers", "White", "#E9EBEF", "PETG"),
    # MatterHackers NylonX / NylonG
    ("MatterHackers", "Black", "#3D3C38", "NylonX"),
    ("MatterHackers", "White", "#DCDED9", "NylonG"),
    # Protopasta HTPLA (from FilamentColors.xyz measured swatches)
    ("Protopasta", "Atikam Teal", "#135859", "HTPLA"),
    ("Protopasta", "Blood of My Enemies", "#7A1A23", "HTPLA"),
    ("Protopasta", "Blue Opaque", "#044A86", "HTPLA"),
    ("Protopasta", "Blue Wonder Glitter Flake", "#20556F", "HTPLA"),
    ("Protopasta", "Bobbi's Purple Iris", "#542B5C", "HTPLA"),
    ("Protopasta", "Brass Composite", "#8C7A4F", "HTPLA"),
    ("Protopasta", "Bronze Composite", "#635146", "HTPLA"),
    ("Protopasta", "Candy Apple Metallic Red", "#A32423", "HTPLA"),
    ("Protopasta", "Cloverleaf Metallic Green", "#245A3F", "HTPLA"),
    ("Protopasta", "Copper Composite", "#976252", "HTPLA"),
    ("Protopasta", "Cupid's Crush Metallic Pink", "#EA8699", "HTPLA"),
    ("Protopasta", "Double Espresso Metallic Brown", "#6B473B", "HTPLA"),
    ("Protopasta", "Dragon Fruit Smoothie", "#B3295F", "HTPLA"),
    ("Protopasta", "Dragon Scale Purple", "#8A80AC", "HTPLA"),
    ("Protopasta", "Dusty Smoke", "#8F9491", "HTPLA"),
    ("Protopasta", "Electric Lemonade Metallic Yellow", "#E4CA6B", "HTPLA"),
    ("Protopasta", "Empire Strikes Metallic Black", "#393B3B", "HTPLA"),
    ("Protopasta", "Fluorescent Yellow", "#D4DC3A", "HTPLA"),
    ("Protopasta", "Galactic Empire Metallic Purple", "#3B3F5D", "HTPLA"),
    ("Protopasta", "Glitter's Mane", "#128C93", "HTPLA"),
    ("Protopasta", "Gold Dust Glitter Flake", "#BFAE6D", "HTPLA"),
    ("Protopasta", "Good as Gold", "#9A774B", "HTPLA"),
    ("Protopasta", "Good Old Gray", "#6D737B", "HTPLA"),
    ("Protopasta", "Green Glowing Natural", "#D4D3AD", "HTPLA"),
    ("Protopasta", "Heartthrob Red Metallic", "#7E3030", "HTPLA"),
    ("Protopasta", "Joel's Highfive Blue", "#056B9A", "HTPLA"),
    ("Protopasta", "Lootsef Green", "#8FB841", "HTPLA"),
    ("Protopasta", "Luke's Proton Purple", "#7D3F59", "HTPLA"),
    ("Protopasta", "Mahogany", "#7F5D4F", "HTPLA"),
    ("Protopasta", "Matte Fiber Black", "#3F3F3E", "HTPLA"),
    ("Protopasta", "Matte Fiber Daffodil", "#B79868", "HTPLA"),
    ("Protopasta", "Matte Fiber Gray", "#767A7D", "HTPLA"),
    ("Protopasta", "Matte Fiber Walnut", "#6F5D4E", "HTPLA"),
    ("Protopasta", "Matte Fiber White", "#F4EADB", "HTPLA"),
    ("Protopasta", "Mermaid's Tale Metallic Teal", "#026768", "HTPLA"),
    ("Protopasta", "Moonstruck White Satin", "#DCE4DD", "HTPLA"),
    ("Protopasta", "Obsidian", "#474743", "HTPLA"),
    ("Protopasta", "Opaque Black", "#312F30", "HTPLA"),
    ("Protopasta", "Opaque Natural", "#CBD0D0", "HTPLA"),
    ("Protopasta", "Opaque White", "#DFE4E2", "HTPLA"),
    ("Protopasta", "Orange Papaya Smoothie", "#C57231", "HTPLA"),
    ("Protopasta", "Out of Darts Orange", "#E58429", "HTPLA"),
    ("Protopasta", "Pineapple Banana Smoothie", "#D0A645", "HTPLA"),
    ("Protopasta", "Pretty in Pink Pearl", "#CE95AE", "HTPLA"),
    ("Protopasta", "Red Hot Cinnamon", "#7C4448", "HTPLA"),
    ("Protopasta", "Red Opaque", "#972425", "HTPLA"),
    ("Protopasta", "Second to None Silver", "#B4B6B6", "HTPLA"),
    ("Protopasta", "Sparkling Spruce", "#47614C", "HTPLA"),
    ("Protopasta", "Stardust Glitter Flake", "#AAB1AE", "HTPLA"),
    ("Protopasta", "Summertime Green", "#89A78A", "HTPLA"),
    ("Protopasta", "Tangerine Orange Metallic Gold", "#C05834", "HTPLA"),
    ("Protopasta", "Translucent Iridescent Ice", "#C4CBC8", "HTPLA"),
    ("Protopasta", "Translucent Silver Smoke", "#A5ACA9", "HTPLA"),
    ("Protopasta", "Unicorn Tears White Glitter", "#D7DEDE", "HTPLA"),
    ("Protopasta", "What Karat? Smooth Gold", "#CD974B", "HTPLA"),
    ("Protopasta", "White", "#F6F5F0", "HTPLA"),
    ("Protopasta", "White Marble", "#C6CECF", "HTPLA"),
    ("Protopasta", "Winter Blue Glitter Flake", "#056F9D", "HTPLA"),
    # Protopasta PLA
    ("Protopasta", "Black", "#323132", "PLA"),
    ("Protopasta", "Conductive", "#373838", "PLA"),
    ("Protopasta", "Iron Composite", "#555451", "PLA"),
    ("Protopasta", "Natural", "#E1DFD6", "PLA"),
    ("Protopasta", "Steel Composite", "#676561", "PLA"),
    # Protopasta Carbon Fiber PLA
    ("Protopasta", "Black", "#424140", "Carbon Fiber PLA"),
    # 3DXTECH (from FilamentColors.xyz measured swatches)
    ("3DXTECH", "Natural", "#DED7C6", "ASA"),
    ("3DXTECH", "Black", "#444342", "Carbon Fiber PLA"),
    ("3DXTECH", "Venom", "#CACC19", "ECOMAX PLA"),
    ("3DXTECH", "Simubone", "#EAE0CB", "PLA"),
    ("3DXTECH", "Blue Frost", "#B1C1C5", "rPETG"),
    # Sakata3D PLA (from FilamentColors.xyz measured swatches)
    ("Sakata3D", "Red", "#B63A32", "PLA"),
    ("Sakata3D", "Silk Sunset", "#F49545", "PLA"),
    ("Sakata3D", "Surf Green", "#00C1A8", "PLA"),
]
